version: '3.6'
services:
  #Nginx
  nginx:
    build: nginx/.
    ports:
     - "8080:80"
    container_name: nginxsrv
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
    depends_on:
      - node1
      - node2
    networks:
      - web-net
  #Nodejs
  node1:
    build: node/.
    ports:
     - "8081:3000"
    container_name: jenkins-app:latest
    environment:
        - REDIS_URL = 172.19.0.2
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
    depends_on:
      - redis
      - git
    networks:
      - redis-net
      - web-net
  node2:
    build: jenkins-app:latest
    ports:
     - "8082:3000"
    container_name: websrv2
    environment:
        - REDIS_URL = 172.19.0.2
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
    depends_on:
      - redis
      - git
    networks:
      - redis-net
      - web-net
  #Redis
  redis:
    image: redis:latest
    container_name: redissrv
    ports:
        - "6379:6379"
    networks:
      - redis-net
    command: ["redis-server", "--appendonly", "yes"]
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
networks:
  redis-net:
  web-net: 